---
- hosts: "es_instances"
  become: yes
  pre_tasks:
    - debug:
        msg: "{{ hostvars[groups['es_instances'][0]].ansible_default_ipv4.address }}:9300"
    - apt_repository:
        repo: "deb http://httpredir.debian.org/debian jessie-backports main contrib non-free"
        update_cache: yes
    - set_fact:
        cluster_alias: "es"
  roles:
    - role: es-role
      vars:
        es_instance_name: "{{ inventory_hostname }}"
        es_config:
          node.name: "{{ inventory_hostname }}"
          cluster.name: "{{ cluster_name }}"
          node.data: "{{ es_node_data }}"
          node.master: "{{ es_node_master }}"
          node.ingest: "{{ es_node_ingest }}"
          discovery.zen.ping.unicast.hosts: "{{ hostvars[groups['es_instances_masters'][0]].ansible_default_ipv4.address }}:9300"
          network.host: "{{ ansible_default_ipv4.address }}"
          transport.tcp.port: 9300
        es_api_host: "{{ ansible_default_ipv4.address }}"
        es_api_port: 9200
